name: CI | Maven Tests | GitFlow | Discord Notification

on:
    # solo se activa cuando ocurre el push
    # como cuando subes de local -> remoto
    # o despues de un PR
    # Ideal para ejecutar en las ramas features
    # que no piden PR y pasaron tests en local
    # No se agrega main y develop para evitar
    # que se active 2 o mas veces el CI
    # pues ya corren en PR el CI
    push:
        branches: [conf, feature/**]
    # PR -> pull request
    # rama remota -> peticion de pull a otra rama
    # (solo peticion, no se ha aprobado)
    # se necesita porque los tests son necesarios
    # para tomar la decision
    pull_request:
        branches: [ main, develop ]

# un job tiene varios steps
# un job por maquina vitual
jobs:
    CI:
        # servidor que se usara para correr los jobs
        runs-on: ubuntu-latest

        steps:
        # remoto -> servidor virtual
        - name: Descargar codigo fuente
          uses: actions/checkout@v4

        # configuracion de java
        - name: Configurar JDK 21 (Temurin)
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: 'maven' # guarda caché de dependencias previas para acelerar pipelines

        - name: Build and test
          run: mvn clean test -Drevision=1.0.0-CI-${{ github.run_number }}-SNAPSHOT

        - name: "Resultado de Build y Tests"
          if: always()
          uses: sarisia/actions-status-discord@v1
          with:
            webhook: ${{ secrets.DISCORD_TESTS_WEBHOOK }}
            # status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'cancelled') && 'cancelled' || 'success' }}
            status: ${{job.status}}
            title: "Resultado de Build y Tests"
            username: ${{github.actor}} Scream :D
            description: "Rama `${{ github.ref_name }}` · Ejecutado por **${{ github.actor }}**"

