name: CI | Maven Tests | GitFlow | Discord Notification

on:
    # local -> remoto
    push:
        branches: [ main ]
    # rama remota -> main remoto
    pull_request:
        branches: [ main ]

# un job tiene varios steps
# un job por maquina vitual
jobs:
    build:
        # servidor que se usara para correr los jobs
        runs-on: ubuntu-latest

        steps:
        # remoto -> servidor virtual
        - name: Descargar codigo fuente
          uses: actions/checkout@v4

        # configuracion de java
        - name: Configurar JDK 21 (Temurin)
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: 'maven' # guarda caché de dependencias previas para acelerar pipelines
    test:
        runs-on: ubuntu-latest

        steps:
        # testeo y sea asigna una version
        - name: Compilar y ejecutar pruebas unitarias con Maven

        # se puede agregar un | para hace run salto de linea
          run: mvn clean test -Drevision=1.0.0-CI-${{ github.run_number }}-SNAPSHOT
    
    notify-pull-requests: 
        name: 'Resultado de build y tests a Discord'
        runs-on: ubuntu-latest
        needs: [build, test]
        if: always()
        steps:
        - name: "Resultado de Build y Tests"
          uses: sarisia/actions-status-discord@v1
          with:
            webhook: ${{ secrets.DISCORD_TESTS_WEBHOOK }}
            status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'cancelled') && 'cancelled' || 'success' }}
            title: "Resultado de Build y Tests"
            content: |
              **Título:** ${{ github.event.pull_request.title }}
              **Autor:** ${{ github.actor }}
              **Origen:** `${{ github.event.pull_request.head.ref }}` ➡️ **Destino:** `${{ github.event.pull_request.base.ref }}`
              [Ver el Pull Request en GitHub](${{ github.event.pull_request.html_url }})
