name: CI | Maven Tests | GitFlow | Discord Notification

on:
    # local -> remoto
    push:
        branches: [main, develop, conf, feature/**]
    # rama remota -> main remoto
    pull_request:
        branches: [ main ]

# un job tiene varios steps
# un job por maquina vitual
jobs:
    CI:
        # servidor que se usara para correr los jobs
        runs-on: ubuntu-latest

        steps:
        # remoto -> servidor virtual
        - name: Descargar codigo fuente
          uses: actions/checkout@v4

        # configuracion de java
        - name: Configurar JDK 21 (Temurin)
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: 'maven' # guarda caché de dependencias previas para acelerar pipelines

        - name: Build
          run: mvn -DskipTests package
        
        - name: test
          run: mvn test -Drevision=1.0.0-CI-${{ github.run_number }}-SNAPSHOT

        - name: "Resultado de Build y Tests"
          if: always()
          uses: sarisia/actions-status-discord@v1
          with:
            webhook: ${{ secrets.DISCORD_TESTS_WEBHOOK }}
            # status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'cancelled') && 'cancelled' || 'success' }}
            status: ${{job.status}}
            title: "Resultado de Build y Tests"
            content: |
              **Título:** ${{ github.event.pull_request.title }}
              **Autor:** ${{ github.actor }}
              **Origen:** `${{ github.event.pull_request.head.ref }}` ➡️ **Destino:** `${{ github.event.pull_request.base.ref }}`
              [Ver el Pull Request en GitHub](${{ github.event.pull_request.html_url }})
